#测试环境###########################################################################################################################################
server:
  port: 8888

spring:
  application:
    name: eureka-server
  profiles:
    active: test #测试环境

# 集群版配置
eureka:
  client:
    fetch-registry: true  # 是否需要从Eureka获取注册信息
    register-with-eureka: true  # 是否需要把该服务注册到Eureka
    service-url: #暴露Eureka注册地址
      defaultZone: http://${IP}:8888/eureka
  instance:
    prefer-ip-address: true  #优先使用该服务的IP地址注册到eureka，在生产环境建议改为true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  server:
    #修改扫描失效服务间隔时间()
    eviction-interval-timer-in-ms: 5000
    #取消自我保护机制
    enable-self-preservation: false