server:
  port: 8086
spring:
  application:
    name: search-picture
  profiles:
    active: test

#elasticsearch
elasticsearch:
  schema: http
  address: 10.16.32.70:9200,10.16.32.113:9200,10.16.32.114:9200
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100

eureka:
  client:
    fetch-registry: true  #作为客户端需要从eureka获取信息
    register-with-eureka: true  #作为客户端注册到eureka
    service-url: #客户端注册地址
      defaultZone: http://10.16.32.151:8888/eureka ,http://10.16.32.155:8888/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true  #优先使用该服务的IP地址注册到eureka，在生产环境建议改为true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
#修改Ribbon负载均衡算法
#MICROSERVICE-USER:
#  ribbon:
#   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true

keycloak:
  enabled: true
  realm: ${spring.profiles.active} #客户端所属领域空间
  principal-attribute: preferred_username #security principal获取token中哪个参数的值
  cors: true #跨域设置
  cors-allowed-methods: POST,PUT,DELETE,GET,OPTIONS,PATCH #跨域设置
  cors-allowed-headers: Authorization, Origin, X-Requested-With, Content-Type #跨域设置
  bearer-only: true #只允许纯token验证方式，其他不支持
  auth-server-url: https://accounts-internal.deepblueai.com/auth #keycloak服务器地址
  ssl-required: external #根据外部访问协议启使用ssl验证
  resource: service-data-center # clientID
  public-client: false #是否公开客户端，公开客户端表示
  always-refresh-token: false #是否对每次请求都刷新访问令牌
  credentials:
    secret: 15194f3e-5cbc-41c2-8729-767d81fdbfd3 #客户端秘钥
  use-resource-role-mappings: true #如果设置为true，适配器将在访问令牌内部查找用户的客户端级角色映射。如果为false，它将查看用户角色映射的领域级别。可选项，默认值为false。
  token-minimum-time-to-live: 3600 #在一个token过期之前的多久（秒）时间提前通过keycloak服务器刷新token